### ISSUE TITLE
Setup kafka and docker

### ISSUE THREAD

**Issue by svacina** [cloudhubs/logscraper#96]
Download:
https://www.docker.com/products/docker-desktop

And after the docker desktop is installed and running, run anywhere from the command line:
```
docker pull wurstmeister/kafka
docker pull wurstmeister/zookeeper
```

Then, clone this repository:

```
git clone https://github.com/wurstmeister/kafka-docker.git 
cd kafka-docker

```

Replace docker-compose.yml file with this content:

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
     - "2181:2181"
  kafka:
    build: .
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
```

Then run:

```
docker-compose up -d
```

After all the images are up, run from the terminal a command that gets you in the console into the docker image:

```
docker exec -i -t -u root $(docker ps | grep docker_kafka | cut -d' ' -f1) /bin/bash
```

And after the previous command, run this command that creates a topic:

```
$KAFKA_HOME/bin/kafka-topics.sh --create --partitions 4 --bootstrap-server kafka:9092 --topic test
```

To exit from the image, run: `exit()` or CTRL-C.

Go to our repository:

```
git checkout master
git pull
# go to venv
pip install -r requirements.txt
# go to repository
cd src
python logconsumer.py
python locproducer.py
```

To close kafka, run:

```
docker-compose stop
```
